### ISSUE TITLE
R Studio Version issue

### ISSUE THREAD

**Issue by RuthSanders** [CenterForAssessment/SGP#1175]
What version of R Studio do I need to run the SGP package. 
I know R SGP is 1.7. 
While running "Demonstration script for 5 steps of the SGP Package" I'm getting issues with the R studio version.
Error Msg:
Error in analyzeSGP(Demonstration_SGP, sgp.percentiles = TRUE, sgp.projections = FALSE,  : 
  could not find function "analyzeSGP"
In addition: Warning message:
R graphics engine version 12 is not supported by this version of RStudio. The Plots tab will be disabled until a newer version of RStudio is installed.

**Comment by dbetebenner** [comment]
Hi Ruth,

I've never seen this before. Are you using the latest version of R Studio? My assumption would be that since it passes all CRAN checks it would work on RStudio. I don't use RStudio but have it installed and will try out the tests. Can you tell me exactly what script you're running that throws this error?
